Repository KIMgyeongmIN00/Hmm-code-review-site, pull requests merged in 2025-02, with the labels that each got.

#2 Chore/#1 project setting
  .gitignore
  .prettierrc
  README.md
  eslint.config.js
  index.html
  package.json
  pnpm-lock.yaml
  src/App.jsx
  src/app/Router.jsx
  src/main.jsx
  src/pages/HomePage.jsx
  src/styles/GlobalStyle.jsx
  vite.config.js
Labels: ⚙ Setting

#10 Feature/#9 common button
  src/components/common/Button.js
  src/styles/GlobalStyle.jsx
Labels: 🎨 Styles, ✨ Feature

#12 Refactor/#11 rename common
  src/components/commons/Button.js
Labels: 🔨 Refactor

#17 Feature/#16 common button link
  eslint.config.js
  src/components/commons/ButtonLink.jsx
  src/styles/GlobalStyle.jsx
Labels: 🎨 Styles, ✨ Feature

#21 Chore/#20 build test action
  .github/workflows/build_test.yml
Labels: ⚙ Setting

#15 Feature/#5-로그인 UI 생성
  package.json
  pnpm-lock.yaml
  src/app/Router.jsx
  src/components/commons/Input.jsx
  src/pages/SigninPage.jsx
  src/styles/GlobalStyle.jsx
Labels: 🎨 Styles

#25 Bugfix/#24 router수정, SignIn 폴더 생성, 이름 통일
  src/app/Router.jsx
  src/pages/sign-in/SignInPage.jsx
Labels: 🐞 BugFix

#7 Feature/#4-헤더UI
  index.html
  public/image/favicon.ico
  public/image/logo.png
  src/components/layouts/header/Header.jsx
  src/components/layouts/header/HomeAuthBtn.jsx
  src/components/layouts/header/HomeMyPageBtn.jsx
  src/components/layouts/header/SearchInput.jsx
  src/pages/HomePage.jsx
  src/styles/GlobalStyle.jsx
  vite.config.js
Labels: 🎨 Styles, ✨ Feature

#33 Feature/#14 필터링UI
  src/components/features/home/HomeLanguageSelector.jsx
  src/components/features/home/HomePost.jsx
  src/components/features/home/HomePostSortRadioGroup.jsx
  src/pages/HomePage.jsx
Labels: 🎨 Styles, ✨ Feature

#34 Feature/#22 auth context
  .gitignore
  package.json
  pnpm-lock.yaml
  src/contexts/auth/AuthProvider.jsx
  src/contexts/auth/auth.context.js
  src/contexts/auth/auth.reducer.js
  src/libs/api/supabase.api.js
  src/main.jsx
Labels: ⚙ Setting, ✨ Feature, 📬 API

#36 feat:#35-MyPageUI구현
  src/app/Router.jsx
  src/pages/MyPage.jsx
Labels: ✨ Feature

#39 Feature/#3 글 작성 페이지 UI
  package.json
  pnpm-lock.yaml
  src/app/Router.jsx
  src/components/commons/SelectBox.jsx
  src/data/programmingLanguage.constant.js
  src/pages/write/WritePage.jsx
Labels: 🎨 Styles, ✨ Feature

#43 bugfix:#13-SelectBox 스크롤 기능 추가
  src/components/commons/SelectBox.jsx
Labels: 🐞 BugFix

#40 Feature/#14 post UI
  src/components/commons/IconButton.jsx
  src/components/commons/PostCard.jsx
  src/components/features/home/HomePost.jsx
  src/pages/HomePage.jsx
  src/styles/GlobalStyle.jsx
Labels: 🎨 Styles, ✨ Feature

#45 Fix/#42 헤더 UI 버그 수정
  src/components/layouts/header/Header.jsx
  src/components/layouts/header/HomeMyPageBtn.jsx
Labels: 🐞 BugFix

#44 Feature/#41 글 작성페이지 로직 추가
  package.json
  pnpm-lock.yaml
  src/pages/write/WritePage.jsx
  src/styles/GlobalStyle.jsx
Labels: ✨ Feature, 📬 API

#37 Feature/#8 글본문UI
  src/app/Router.jsx
  src/components/commons/Button.js
  src/components/commons/SelectBox.jsx
  src/components/features/view-page/CommentAreaContainer.jsx
  src/components/features/view-page/PostAreaContainer.jsx
  src/components/features/view-page/in-comment-area-container/CommentAddContainer.jsx
  src/components/features/view-page/in-comment-area-container/CommentBoxContainer.jsx
  src/components/features/view-page/in-comment-area-container/CommentOnAuthButtons.jsx
  src/components/features/view-page/in-post-area-container/PostOnAuthButtons.jsx
  src/pages/view/ViewPage.jsx
  src/styles/GlobalStyle.jsx
Labels: 🎨 Styles, ✨ Feature

#50 Feature/#46 헤더 네비게이팅 설정
  src/components/layouts/header/Header.jsx
  src/components/layouts/header/HomeAuthBtn.jsx
  src/components/layouts/header/HomeMyPageBtn.jsx
Labels: ✨ Feature

#47 feat: #38 signUp 페이지 UI 구현
  src/app/Router.jsx
  src/components/commons/Input.jsx
  src/pages/sign-in/SignInPage.jsx
  src/pages/sign-up/SignUpInput.jsx
  src/pages/sign-up/SignUpPage.jsx
Labels: 🎨 Styles, ✨ Feature

#53 Feature/#49 사용자 auth 상태 적용
  src/components/layouts/header/Header.jsx
  src/components/layouts/header/HomeMyPageBtn.jsx
  src/pages/HomePage.jsx
Labels: ✨ Feature

#56 Chore/#52 vercel.json 파일 생성및설정
  vercel.json
Labels: ⚙ Setting, 🌏 Deploy

#61 Feature/#46 post view 페이지 이동
  src/components/commons/PostCard.jsx
  src/libs/api/supabase.api.js
  src/pages/HomePage.jsx
  src/utils/formatDate.js
Labels: 🎨 Styles, ✨ Feature

#65 Feature/#62 프로그래밍 언어 필터링
  src/components/features/home/HomeLanguageSelector.jsx
  src/pages/HomePage.jsx
Labels: ✨ Feature

#66 Feature#58 protected router
  src/app/ProtectedRouter.jsx
  src/app/Router.jsx
  src/components/layouts/header/HomeMyPageBtn.jsx
  src/contexts/auth/AuthProvider.jsx
  src/contexts/auth/auth.reducer.js
  src/hooks/auth/useSignInForm.js
  src/main.jsx
  src/pages/sign-in/SignInPage.jsx
Labels: 🐞 BugFix

#64 Feature/#63 소셜 로그인
  public/image/googleLogo.png
  src/contexts/auth/AuthProvider.jsx
  src/pages/sign-in/SignInPage.jsx
Labels: ✨ Feature, 📬 API

#69 Fix/#68-PostCard 수정
  src/components/commons/PostCard.jsx
Labels: 🐞 BugFix

#67 Feature/#51 signUpPage 기능 구현
  src/hooks/auth/useQuestions.js
  src/hooks/auth/useSignUpForm.js
  src/libs/utils/signUpValidate.js
  src/pages/sign-up/SignUpForm.jsx
  src/pages/sign-up/SignUpInput.jsx
  src/pages/sign-up/SignUpPage.jsx
Labels: ✨ Feature, 📬 API

#72 Fix/#71 로그인 이슈 해결
  src/contexts/auth/AuthProvider.jsx
Labels: 🐞 BugFix

#74 Feature/#62 radio group 정렬
  src/components/features/home/HomeLanguageSelector.jsx
  src/components/features/home/HomePostSortRadioGroup.jsx
  src/pages/HomePage.jsx
Labels: ✨ Feature

#80 Feature/#76 signUp 예외처리
  src/hooks/auth/useSignUpForm.js
  src/libs/utils/signUpValidate.js
  src/pages/sign-up/SignUpForm.jsx
Labels: ✨ Feature, 📬 API

#86 Refactor/#82-이메일_수정_불가_처리
  src/pages/MyPage.jsx
Labels: 🔨 Refactor

#83 Feature/#75 검색 기능 구현
  src/components/layouts/header/Header.jsx
  src/pages/HomePage.jsx
Labels: ✨ Feature
